static pointer CLO4553();
static pointer CLO4665();
static pointer CLO4668();
static pointer CLO4722();
static pointer CLO4724();
static pointer CLO4745();
static pointer CLO4774();
static pointer FLET4776();
static pointer CLO4778();
static pointer (*ftab[13])();

#define QUOTE_STRINGS_SIZE 97
static char *quote_strings[QUOTE_STRINGS_SIZE]={
    ":inside",
    "*coplanar-threshold*",
    ":all-edges",
    ":intersect-line",
    ":colinear",
    ":insidep",
    "<=",
    "eps<",
    ":point",
    "eps<>",
    "*contact-threshold*",
    "face",
    ":count",
    "delete",
    "eps-v=",
    "make-line",
    "car",
    "face-normal-vector",
    ":init",
    ":vertices",
    "hole",
    ":face",
    ":enter-hole",
    "line",
    ":vertex",
    ":normal",
    ":direction",
    "cddr",
    ":test",
    "remove-duplicates",
    "every",
    ":outside",
    "rest",
    ":intersection",
    "eps=",
    "((:border . :contact) (:inside . :contact) (:outside))",
    "assoc",
    ":on-plane-p",
    ":contact",
    ":intersect",
    ":border",
    ":coplanar",
    ":equidirection",
    ":opposing",
    "some",
    ":aligned",
    "\";; ~s and ~s intersected~%\"",
    "\";; ~s and ~s intersected~%\"",
    ":point/edge-contact",
    "*epsilon*",
    ":common-box",
    ":curved-faces",
    ":possibly-interfering-faces",
    "intersection",
    ":possibly-interfering-edges",
    ":box",
    ":grow",
    ":intersection-p",
    ":planar-contact",
    "*face-class*",
    ":holes",
    "\"GEOMETRY\"",
    "\"GEOMETRY\"",
    "*package*",
    "\"no such package\"",
    "(face+ face* ff-relation bb-relation)",
    "coplanar-fe-intersection",
    "\"(face1 edge2 &opt side tol) edge2 is coplanar with face1.\ncoplanar-fe-intersection finds all the line-to-line intersection between\nedge2 and all the edges forming face1\"",
    "find-next-segment",
    "\"(nv segs tol)\"",
    "find-loop",
    "\"(segments normal &optional (tol *contact-threshold*))\"",
    "punch-hole",
    "\"(profile hole-polygon)\"",
    "construct-polygon",
    "\"(segments normal &optional (tol *contact-threshold*))\"",
    "remove-non-overlapping-border",
    "\"(face1 face2 colinears)\"",
    "coplanar-ff-intersection",
    "\"(face1 face2 &optional (side :inside) (tol *coplanar-threshold*))\"",
    "face*",
    "\"(f1 f2 &optional (tolerance *coplanar-threshold*))\"",
    "face+",
    "\"(f1 f2 &optional (tolerance *coplanar-threshold*))\"",
    "non-coplanar-fe-relation",
    "\"(face1 edge2 &optional (tolerance *coplanar-threshold*))\"",
    "ff-relation",
    "\"(face1 face2 &optional (tolerance *coplanar-threshold*))\"",
    "bb-relation",
    "\"(body1 body2 &optional (tolerance *epsilon*))\"",
    "make-lines",
    "\"(point-pairs)\"",
    "copy-face",
    "\"(f)\"",
    ":bodyrel",
    "\"@(#)$Id$\"",
    "provide",
  };
